Translated the front readme file
arduino/reference-cs pull request #4
Opened 2019-05-14 14:38 UTC by TomasRoj

I am not sure if I did everything correctly so I am open to any questions or rewievs. Hope this helps!

2019-05-14 16:02 UTC, per1234 requested changes

2019-05-14 16:02 UTC, per1234 commented on README.adoc
> -In https://raw.githubusercontent.com/arduino/reference-cz/master/AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc[`reference-cz/AsciiDoc_sample/AsciiDoc_Dictionary`] you will fin
You forgot to translate this line. You only deleted it.

2019-05-14 16:02 UTC, per1234 commented on README.adoc
> +Pokud potřebuješ přidat obrázky do ASCII dokumentu, prosím vytvoř složku pojmenovanou "attachments" ve stejné složce, jako je ASCII dokument. Obrázku mohou být uloženy v SVG nebo PNG formátu (ne JPG!
Don't translate the word "Asciidoc". This is a name of a markup format and so the word is the same in any language. You'll need to be careful about this sort of thing throughout your translations. For example, you would not want to translate code syntax. You should translate string literals and comments in the code. You can translate variable names in the example code if you like, though you should make sure to translate all occurrences of the variable name in the code.

2019-05-14 16:16 UTC, TomasRoj commented on README.adoc
> +Pokud potřebuješ přidat obrázky do ASCII dokumentu, prosím vytvoř složku pojmenovanou "attachments" ve stejné složce, jako je ASCII dokument. Obrázku mohou být uloženy v SVG nebo PNG formátu (ne JPG!
Ok, fixed

2019-05-14 16:22 UTC, TomasRoj commented on README.adoc
> -In https://raw.githubusercontent.com/arduino/reference-cz/master/AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc[`reference-cz/AsciiDoc_sample/AsciiDoc_Dictionary`] you will fin
Ok, this too

2019-05-14 16:35 UTC, per1234 commented on README.adoc
> +Pokud potřebuješ přidat obrázky do ASCII dokumentu, prosím vytvoř složku pojmenovanou "attachments" ve stejné složce, jako je ASCII dokument. Obrázku mohou být uloženy v SVG nebo PNG formátu (ne JPG!
You added the translation of this line in the wrong place in the text. It should be part of the paragraph before the bullet points.

2019-05-14 16:36 UTC, per1234 commented on README.adoc
> -In https://raw.githubusercontent.com/arduino/reference-cz/master/AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc[`reference-cz/AsciiDoc_sample/AsciiDoc_Dictionary`] you will fin
You added the translation of this line in the wrong place in the text. It should be part of the paragraph before the bullet points.

2019-05-14 16:47 UTC, TomasRoj commented
I don't understand what do you mean by this

2019-05-14 16:55 UTC, per1234 commented on README.adoc
> -In https://raw.githubusercontent.com/arduino/reference-cz/master/AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc[`reference-cz/AsciiDoc_sample/AsciiDoc_Dictionary`] you will fin
Here is the position of the sentence before the translation, in the paragraph before the bullet points:

---
![en](https://user-images.githubusercontent.com/8572152/57716553-20a88900-762e-11e9-9de7-19a1b4134d78.png)

---
Here is the position of the sentence after the translation, after the bullet points:

---
![cs](https://user-images.githubusercontent.com/8572152/57716569-2a31f100-762e-11e9-905c-3c57f2adf712.png)

---

2019-05-14 17:10 UTC, TomasRoj commented on README.adoc
> -In https://raw.githubusercontent.com/arduino/reference-cz/master/AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc[`reference-cz/AsciiDoc_sample/AsciiDoc_Dictionary`] you will fin
Ok thanks for your drawings! I understand now.

2019-05-14 17:13 UTC, TomasRoj commented
Is now everything ok?

2019-05-14 20:12 UTC, per1234 approved these changes

2019-05-14 20:13 UTC, merged

2019-05-14 20:14 UTC, per1234 commented
Thanks so much @TomasRoj! Great work.

2019-05-15 05:27 UTC, TomasRoj commented
Thx. I cannot believe that I made contribution to official arduino account 😂